"use client";

import { CheckCircle, MailX, Sparkles } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { BrandLogo } from "@/components/brand-logo";
import { request } from "@/lib/api";

export default function VerifyEmailPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const email = searchParams.get("email");
  const token = searchParams.get("token");

  const [loading, setLoading] = useState(true);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    const verify = async () => {
      try {
        await request("/api/users/verify-email", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ email, token }),
        });
        setSuccess(true);
        window.setTimeout(() => router.push("/login"), 1600);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Email verification failed.");
      } finally {
        setLoading(false);
      }
    };

    if (email && token) {
      verify();
    } else {
      setError("Invalid verification link.");
      setLoading(false);
    }
  }, [email, token, router]);

  return (
    <section className="relative min-h-screen overflow-hidden text-[color:var(--text-dark)]">
      <div className="absolute inset-0 bg-[linear-gradient(180deg,#ffffff_0%,#f7fbff_56%,#edf5fb_100%)]" />
      <div className="mesh-bg opacity-70" />
      <div className="hero-grid absolute inset-0 opacity-[0.07]" />

      <div className="page-container relative z-10 py-6 sm:py-10">
        <div className="mx-auto grid min-h-[88vh] max-w-5xl overflow-hidden rounded-[1.8rem] border border-[rgba(15,76,129,0.08)] bg-[linear-gradient(180deg,rgba(255,255,255,0.96),rgba(247,251,255,0.95))] shadow-[0_30px_80px_rgba(4,12,26,0.14)] lg:grid-cols-[0.95fr_1.05fr] lg:rounded-[2.2rem]">
          <aside className="relative hidden overflow-hidden border-r border-[rgba(15,76,129,0.08)] p-6 lg:flex lg:flex-col lg:justify-between xl:p-8">
            <div className="absolute left-[-4rem] top-12 h-44 w-44 rounded-full bg-[rgba(60,126,182,0.1)] blur-3xl" />
            <div className="absolute bottom-0 right-[-3rem] h-40 w-40 rounded-full bg-[rgba(255,138,61,0.12)] blur-3xl" />

            <div className="relative z-10">
              <BrandLogo textColor="dark" className="h-10" />
              <div className="mt-5 inline-flex rounded-full border border-[rgba(15,76,129,0.12)] bg-[rgba(15,76,129,0.06)] px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] text-[color:var(--brand-primary)]">
                <Sparkles className="mr-2 size-3.5" />
                Email Verification
              </div>
            </div>

            <div className="relative z-10 rounded-[2rem] border border-[rgba(15,76,129,0.1)] bg-[linear-gradient(180deg,#ffffff,#eff6ff)] p-8 shadow-[0_22px_50px_rgba(22,50,79,0.1)]">
              <CheckCircle className="mb-5 size-12 text-[color:var(--brand-primary)]" />
              <h2 className="font-[family:var(--font-display)] text-3xl leading-none text-[color:var(--text-dark)]">
                Activate your account
              </h2>
              <p className="mt-4 text-sm leading-7 text-[color:var(--text-muted)]">
                Verify your email to continue securely and complete your access flow.
              </p>
            </div>

            <p className="relative z-10 max-w-sm text-sm leading-7 text-[color:var(--text-muted)]">
              This route is directly compatible with verification links generated by
              the backend.
            </p>
          </aside>

          <main className="flex items-center justify-center p-5 sm:p-8 lg:p-10">
            <div className="w-full max-w-md text-center">
              <BrandLogo variant="tab" className="mx-auto mb-4" />

              {loading ? (
                <div className="rounded-[1.5rem] border border-[rgba(15,76,129,0.08)] bg-white px-6 py-8 shadow-[0_18px_40px_rgba(22,50,79,0.08)]">
                  <p className="text-lg font-medium text-[color:var(--text-dark)]">
                    Verifying your email...
                  </p>
                </div>
              ) : null}

              {!loading && success ? (
                <div className="rounded-[1.5rem] border border-emerald-200 bg-emerald-50 px-6 py-8">
                  <CheckCircle className="mx-auto mb-3 size-10 text-emerald-600" />
                  <h1 className="text-xl font-semibold text-emerald-700">Email verified successfully</h1>
                  <p className="mt-2 text-sm text-emerald-700">Redirecting to login...</p>
                </div>
              ) : null}

              {!loading && error ? (
                <div className="rounded-[1.5rem] border border-red-200 bg-red-50 px-6 py-8">
                  <MailX className="mx-auto mb-3 size-10 text-red-600" />
                  <h1 className="text-xl font-semibold text-red-700">Verification failed</h1>
                  <p className="mt-2 text-sm text-red-700">{error}</p>
                  <Link
                    href="/login"
                    className="mt-4 inline-block text-sm font-semibold text-[color:var(--brand-primary)] hover:text-[color:var(--brand-primary-soft)]"
                  >
                    Back to login
                  </Link>
                </div>
              ) : null}
            </div>
          </main>
        </div>
      </div>
    </section>
  );
}
